### ISSUE TITLE
[BUG] Invalid Useragent // Cloudflare

### ISSUE THREAD

**Issue by LilSizzurp** [Lightcord/Lightcord#11]
**Describe the bug**
The bot API requests don't use the correct user-agent header and trigger a cloudflare 403 block.

**To Reproduce**
1. Log in as a bot
2. Look in devconsole network
3. Not all the cloudflare bot 403's

**Expected behavior**
API calls go through.

**Screenshots**
![](https://i.pxl.blue/1b6B73e.png)
![](https://i.pxl.blue/F8dec7C.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v0.1.4

**Additional context**
You need to use the `DiscordBot` useragent. [Docs Reference](https://discord.com/developers/docs/reference#user-agent)

**Comment by JeanOUINA** [comment]
Thank you for your issue.

If you really want to use bots, you can use our dev versions that fix this issue:

**BETA/DEV/BLEEDING EDGE VERSIONS**
Windows: https://lightcord.deroku.xyz/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip
Linux: https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip

No mac version, sorry.

This issue will be fixed in our next release.
