### ISSUE TITLE
[BUG] Channels don't load with bot login

### ISSUE THREAD

**Issue by Cr3atable** [Lightcord/Lightcord#22]
**Describe the bug**
Bots don't render messages in channels.

**To Reproduce**
1. Login with a bot token (you have to manually do this as the login screen doesn't work with tokens)
2. Click on a server
3. Click on a channel

**Expected behavior**
The channel should render messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/31049082/90472194-f9245400-e0ed-11ea-9da6-42a704910ee8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.1.4 (80b2b93)

**Comment by phorcysed** [comment]
#11 Duplicate,

This is a problem related to us not using the `DiscordBot` UserAgent.

If you really want to use bots, you can use our dev versions that fix this issue, but they probably will have more bugs:

**BETA/DEV/BLEEDING EDGE VERSIONS**
Windows: https://lightcord.deroku.xyz/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip
Linux: https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip

No mac version, sorry.

This issue will still be fixed in our next release.
