### ISSUE TITLE
Code that executes when a message is sent

### ISSUE THREAD

**Issue by XiovV** [Lightcord/Lightcord#264]
Hi there, I'm trying to figure out what line of code is executed when a user presses enter to send a message. The reason why is because I'd like to modify the message content before sending it. I found a function called
createMessage(message:DiscordMessage):Message inside DiscordJS/src/util/util.ts, but after testing for a bit I don't think that's what I'm looking for.

**Comment by smartfrigde** [comment]
Hi there, I'm trying to figure out what line of code is executed when a user presses enter to send a message. The reason why is because I'd like to modify the message content before sending it. I found a function called
createMessage(message:DiscordMessage):Message inside DiscordJS/src/util/util.ts, but after testing for a bit I don't think that's what I'm looking for.

**Comment by XiovV** [comment]
@smartfrigde ¯\_(ツ)_/¯

**Comment by JeanOUINA** [comment]
you need to search in Discord’s code. The function isn’t in Lightcord’s

**Comment by XiovV** [comment]
@JeanOUINA I'm assuming that's in discord_desktop_core?

**Comment by JeanOUINA** [comment]
no, that's in the discord.com source code
