### ISSUE TITLE
[BUG]Program becomes unresponsive several minutes after being opened

### ISSUE THREAD

**Issue by asorel1942** [Lightcord/Lightcord#42]
After a few minutes of use, Lightcord freezes and becomes unresponsive; the only way to resolve the issue is to force-close the program through the task manager and open it again. Disabling all plugins, disabling custom theme, and a clean reinstall of the program does not solve the issue. Attempted on Manjaro Linux 64-bit, details attached below:

![image](https://user-images.githubusercontent.com/33983895/93795444-605e8800-fc07-11ea-85e9-f1b7179cbcbc.png)

**Comment by asorel1942** [comment]
A brief test shows that this issue occurs with the official Discord app as well, downloaded from the Manjaro official repositories, suggesting that this is an issue with Discord itself and not Lightcord.

**Comment by JeanOUINA** [comment]
looks like lightcord isn’t injected in the main window ?

Can you send a screenshot of logs (ctrl+shift+i and then in the console tab) ?

**Comment by asorel1942** [comment]
Attached are the logs screenshots, from lightcord's startup up to the point when it froze. I've also found that the cause of the freeze is the receiving of a new notification.

![Screenshot_20200921_141551](https://user-images.githubusercontent.com/33983895/93805642-01543f80-fc16-11ea-9379-819800f7262c.png)
![Screenshot_20200921_141536](https://user-images.githubusercontent.com/33983895/93805644-01ecd600-fc16-11ea-969b-53e274349581.png)
![Screenshot_20200921_141859](https://user-images.githubusercontent.com/33983895/93805646-02856c80-fc16-11ea-9609-8f8d9ae3ce17.png)
![Screenshot_20200921_141512](https://user-images.githubusercontent.com/33983895/93805647-02856c80-fc16-11ea-83c4-0c5c3bf37e86.png)
![Screenshot_20200921_141527](https://user-images.githubusercontent.com/33983895/93805649-031e0300-fc16-11ea-9596-391ad31a4833.png)

**Comment by asorel1942** [comment]
One more update: it appears that the program will eventually unfreeze after receiving a notification, however it takes several minutes before it is responsive again.

**Comment by Quist0n** [comment]
**Preamble:**
I have had this issue as well. I am going to assume that you are running a more minimalist system and have not implemented a notification system.

**Problem:**
It is caused by discord trying to send off a notification and not being able to, something internally just makes the entire program hang and wait until it either gets an response or just times out. 

To test, open up a terminal and launch discord from there, do something that will get you a notification and check the output in the terminal. It will give you some error about _libnotify_. If it does give you that message then follow the steps please.

**How to Solve:**
1. Go to the [arch wiki's page on setting up a notification system](https://wiki.archlinux.org/index.php/Desktop_notifications) and follow their steps.

2. Pick a notification system you like and set that up as well.

3. Profit.

I hope this helps you out.

**Comment by asorel1942** [comment]
@Quist0n thanks, that's helpful. For whatever reason, it seems like I don't have the Notifications widget for Manjaro installed, which is what's causing the error.

**Comment by pryme-svg** [comment]
Try doing `notify-send [test-message]` and see what errors you get
