### ISSUE TITLE
[BUG] The token field on the login page cannot be written to

### ISSUE THREAD

**Issue by MPeti1** [Lightcord/Lightcord#53]
**Describe the bug**
When you are on the login page after installation, there's an option to connect with token.
This field does not change either if I try to type while it's selected, nor when I try to paste into it

**To Reproduce**
1. Install Lightcord with the installer exe on a Windows system
2. Wait until your browser opens
3. When (if) Lightcord noticed that there's no discord account logged in there, it'll prompt you the login page
4. Try to type or paste to the token field on the right
5. The token field will stay empty

**Expected behavior**
The token field should get filled as I type/paste

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.1.4

**Comment by JeanOUINA** [comment]
Thank you for your issue. 

The token field is correctly listening to inputs, it just doesn't show because of a display bug.
It's currently fixed in the main branch, here are downloads links:
[Windows Installer](https://cdn.discordapp.com/attachments/706080103674937375/765848386652995604/LightcordSetup.exe)
[Windows](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip)
[Windows Portable](https://lightcord.org/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32.exe)
[Linux](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip)
[Mac](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-darwin.zip)

**Comment by MPeti1** [comment]
Thank you!
Now I feel a bit bad that I've written this duplicate without first searching in the closed issues too. Sorry!
