### ISSUE TITLE
an error occured [BUG]

### ISSUE THREAD

**Issue by ZPenux** [Lightcord/Lightcord#54]
its eveywhere 
in: 
![Screenshot_134](https://user-images.githubusercontent.com/70713896/96117186-fb3a4180-0ee9-11eb-8321-a00149d07a14.png)
![Screenshot_135](https://user-images.githubusercontent.com/70713896/96117198-fffef580-0ee9-11eb-9ccf-46b6dee0987f.png)
![Screenshot_136](https://user-images.githubusercontent.com/70713896/96117201-01302280-0eea-11eb-837d-63e566e248f6.png)

lightcord settings , richpresence , betterdiscord settings

**Comment by JeanOUINA** [comment]
Thank you for your issue. 

It's currently fixed in the main branch, here are downloads links:
[Windows Installer](https://cdn.discordapp.com/attachments/706080103674937375/765848386652995604/LightcordSetup.exe)
[Windows](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip)
[Windows Portable](https://lightcord.org/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32.exe)
[Linux](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip)
[Mac](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-darwin.zip)

I’m pinning this issue because it’s a frequently reported bug.

**Comment by Oof4** [comment]
WAIT IT HAPPENED TO ME ASWELL

**Comment by Nesrin358** [comment]
H

**Comment by msPornHub** [comment]
shut up nigger

**Comment by asorel1942** [comment]
> Thank you for your issue.
> 
> It's currently fixed in the main branch, here are downloads links:
> [Windows Installer](https://cdn.discordapp.com/attachments/706080103674937375/765848386652995604/LightcordSetup.exe)
> [Windows](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip)
> [Windows Portable](https://lightcord.org/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32.exe)
> [Linux](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip)
> [Mac](https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-darwin.zip)
> 
> I’m pinning this issue because it’s a frequently reported bug.

When will this be integrated into the AUR release? Alternatively, what are the install directions for manually upgrading using the install link?

**Comment by ControlAlternateDelete** [comment]
I'm still getting this issue even with this version installed
