### ISSUE TITLE
AUR Package for Arch-based distros

### ISSUE THREAD

**Issue by nephitejnf** [Lightcord/Lightcord#7]
I've put together a PKGBUILD for Arch users for this.
https://aur.archlinux.org/packages/lightcord-bin/

If you wanna add it to the README so those people don't have to think about it down the road.

**Comment by phorcysed** [comment]
me when shouldn't the ver be "v0.1.3" instead of v0.1.3, but yeah i'm adding it. It already is in the discord though.

**Comment by PoorPocketsMcNewHold** [comment]
@nephitejnf Would probably be a lot mopre usefull, if you could add a .desktop file to it instead of having to execute it from /usr/share everytime. 

Feel free to take mine from my PKG attempt. I was only having issues with the file rights that you’ve solved in your PKG.

https://github.com/PoorPocketsMcNewHold/Lightcord-PKGBUILD

**Comment by nephitejnf** [comment]
Cool, sorry, I use a WM so a .desktop never quite crossed my mind.

**Comment by nephitejnf** [comment]
Added and updated. Should make it easier on people now.

**Comment by phorcysed** [comment]
well done guys!
