### ISSUE TITLE
Lightcord logs out too many times

### ISSUE THREAD

**Issue by Oof4** [Lightcord/Lightcord#74]
when i restart my computer or device 2 times, it keeps logging me out

**Comment by msPornHub** [comment]
dont change password for logout

**Comment by JeanOUINA** [comment]
if you don’t close lightcord properly (the X button), it will logout because discord removes the token from the storage when running, and if it isn’t closed properly, it can’t store it before the process exits

**Comment by Liz-chan** [comment]
Isn't there a way to force the token to be kept in storage so that that doesn't happen?

**Comment by JeanOUINA** [comment]
Yes (the showToken function on the AuthenticationStore, or just block Discord from removing it), but it can be viewed as a security risks.
For example, if you show the token, then create an iframe to discord, you can now read the localStorage in the iframe (because the localStorage is removed in Discord’s context, but not in the iframe) and the token is inside. That can actually bypass all sorts of sandboxing.

I’ll probably add an option in one of the next versions, but at the user’s own risks.
