### ISSUE TITLE
No Windows 10 Toast Notifications

### ISSUE THREAD

**Issue by BaalEvan** [Lightcord/Lightcord#8]
There is no Lightcord in Notification Settings in Windows 10, and there is no Toast notification.

I think it's because there is no Installed PackageManifest with notification capabilities or something in system.

**Comment by JeanOUINA** [comment]
I think it's because we do not use Windows Notifications on windows, but we use a transparent `BrowserWindow` instead. There was issues with using Windows Notifications.

I'm looking at it right now, It seems that Windows Notifications work on dev version. 
![notification](https://i.imgur.com/I6maSDX.png)
![notification settings](https://i.imgur.com/JjKHq4L.png)
I'll check on packaged one in about 20 minutes to see whether or not I enable it.

**Comment by JeanOUINA** [comment]
It seems it works, I'll add in next release
